---
apiVersion: v1
kind: Secret
metadata:
  name: ops-manager-organization-apikey
type: Opaque
stringData:
  # Public Key
  user: HETDYSDB
  # Private Key
  publicApiKey: 1c4156bb-1ab0-49b4-af25-fe260800987b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-manager-example-mongo-config
data:
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080
  orgId: 5f8b4a11a44fb00072e464c6
  projectName: example-project