---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-mongo-0
spec:
  secretName: example-mongo-0
  duration: 87600h
  issuerRef:
    name: mongodb-ca-issuer
    kind: Issuer
  commonName: "*.example-mongo-svc.mongodb.svc.cluster.local"
  organization:
  - My Organization
  dnsNames:
  - example-mongo-0.example-mongo-svc.mongodb.svc.cluster.local
  privateKey:
    rotationPolicy: Always
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-mongo-1
spec:
  secretName: example-mongo-1
  duration: 87600h
  issuerRef:
    name: mongodb-ca-issuer
    kind: Issuer
  commonName: "*.example-mongo-svc.mongodb.svc.cluster.local"
  organization:
  - My Organization
  dnsNames:
  - example-mongo-1.example-mongo-svc.mongodb.svc.cluster.local
  privateKey:
    rotationPolicy: Always
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-mongo-2
spec:
  secretName: example-mongo-2
  duration: 87600h
  issuerRef:
    name: mongodb-ca-issuer
    kind: Issuer
  commonName: "*.example-mongo-svc.mongodb.svc.cluster.local"
  organization:
  - My Organization
  dnsNames:
  - example-mongo-2.example-mongo-svc.mongodb.svc.cluster.local
  privateKey:
    rotationPolicy: Always